config/routes.rb
PStatus::Application.routes.draw do
  resources :deliverables

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users, :only => [:show, :index]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/deliverable.rb
class Deliverable < ActiveRecord::Base
  attr_accessible :cumulative_time_resourcewise, :cumulative_time_taskwise, :description, :estimated_task_resource_time, :estimated_task_time, :production_release, :project, :qa_release, :release, :task_sl, :task_type, :ticket, :week_actual_effort, :week_projected_effort, :work_list
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end
end

app/controllers/deliverables_controller.rb
class DeliverablesController < ApplicationController
  # GET /deliverables
  # GET /deliverables.json
  def index
    @deliverables = Deliverable.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @deliverables }
    end
  end

  # GET /deliverables/1
  # GET /deliverables/1.json
  def show
    @deliverable = Deliverable.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @deliverable }
    end
  end

  # GET /deliverables/new
  # GET /deliverables/new.json
  def new
    @deliverable = Deliverable.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @deliverable }
    end
  end

  # GET /deliverables/1/edit
  def edit
    @deliverable = Deliverable.find(params[:id])
  end

  # POST /deliverables
  # POST /deliverables.json
  def create
    @deliverable = Deliverable.new(params[:deliverable])

    respond_to do |format|
      if @deliverable.save
        format.html { redirect_to @deliverable, notice: 'Deliverable was successfully created.' }
        format.json { render json: @deliverable, status: :created, location: @deliverable }
      else
        format.html { render action: "new" }
        format.json { render json: @deliverable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /deliverables/1
  # PUT /deliverables/1.json
  def update
    @deliverable = Deliverable.find(params[:id])

    respond_to do |format|
      if @deliverable.update_attributes(params[:deliverable])
        format.html { redirect_to @deliverable, notice: 'Deliverable was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @deliverable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deliverables/1
  # DELETE /deliverables/1.json
  def destroy
    @deliverable = Deliverable.find(params[:id])
    @deliverable.destroy

    respond_to do |format|
      format.html { redirect_to deliverables_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deliverables_helper.rb
module DeliverablesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/deliverables/_form.html.erb
<%= form_for(@deliverable) do |f| %>
  <% if @deliverable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deliverable.errors.count, "error") %> prohibited this deliverable from being saved:</h2>

      <ul>
      <% @deliverable.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :task_sl %><br />
    <%= f.number_field :task_sl %>
  </div>
  <div class="field">
    <%= f.label :task_type %><br />
    <%= f.text_field :task_type %>
  </div>
  <div class="field">
    <%= f.label :project %><br />
    <%= f.text_field :project %>
  </div>
  <div class="field">
    <%= f.label :ticket %><br />
    <%= f.number_field :ticket %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :estimated_task_time %><br />
    <%= f.text_field :estimated_task_time %>
  </div>
  <div class="field">
    <%= f.label :estimated_task_resource_time %><br />
    <%= f.text_field :estimated_task_resource_time %>
  </div>
  <div class="field">
    <%= f.label :cumulative_time_taskwise %><br />
    <%= f.text_field :cumulative_time_taskwise %>
  </div>
  <div class="field">
    <%= f.label :cumulative_time_resourcewise %><br />
    <%= f.text_field :cumulative_time_resourcewise %>
  </div>
  <div class="field">
    <%= f.label :week_projected_effort %><br />
    <%= f.text_field :week_projected_effort %>
  </div>
  <div class="field">
    <%= f.label :week_actual_effort %><br />
    <%= f.text_field :week_actual_effort %>
  </div>
  <div class="field">
    <%= f.label :qa_release %><br />
    <%= f.date_select :qa_release %>
  </div>
  <div class="field">
    <%= f.label :production_release %><br />
    <%= f.date_select :production_release %>
  </div>
  <div class="field">
    <%= f.label :release %><br />
    <%= f.text_field :release %>
  </div>
  <div class="field">
    <%= f.label :work_list %><br />
    <%= f.text_field :work_list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/deliverables/edit.html.erb
<h1>Editing deliverable</h1>

<%= render 'form' %>

<%= link_to 'Show', @deliverable %> |
<%= link_to 'Back', deliverables_path %>

app/views/deliverables/index.html.erb
<h1>Listing deliverables</h1>

<table>
  <tr>
    <th>Task sl</th>
    <th>Task type</th>
    <th>Project</th>
    <th>Ticket</th>
    <th>Description</th>
    <th>Estimated task time</th>
    <th>Estimated task resource time</th>
    <th>Cumulative time taskwise</th>
    <th>Cumulative time resourcewise</th>
    <th>Week projected effort</th>
    <th>Week actual effort</th>
    <th>Qa release</th>
    <th>Production release</th>
    <th>Release</th>
    <th>Work list</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @deliverables.each do |deliverable| %>
  <tr>
    <td><%= deliverable.task_sl %></td>
    <td><%= deliverable.task_type %></td>
    <td><%= deliverable.project %></td>
    <td><%= deliverable.ticket %></td>
    <td><%= deliverable.description %></td>
    <td><%= deliverable.estimated_task_time %></td>
    <td><%= deliverable.estimated_task_resource_time %></td>
    <td><%= deliverable.cumulative_time_taskwise %></td>
    <td><%= deliverable.cumulative_time_resourcewise %></td>
    <td><%= deliverable.week_projected_effort %></td>
    <td><%= deliverable.week_actual_effort %></td>
    <td><%= deliverable.qa_release %></td>
    <td><%= deliverable.production_release %></td>
    <td><%= deliverable.release %></td>
    <td><%= deliverable.work_list %></td>
    <td><%= link_to 'Show', deliverable %></td>
    <td><%= link_to 'Edit', edit_deliverable_path(deliverable) %></td>
    <td><%= link_to 'Destroy', deliverable, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Deliverable', new_deliverable_path %>

app/views/deliverables/new.html.erb
<h1>New deliverable</h1>

<%= render 'form' %>

<%= link_to 'Back', deliverables_path %>

app/views/deliverables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Task sl:</b>
  <%= @deliverable.task_sl %>
</p>

<p>
  <b>Task type:</b>
  <%= @deliverable.task_type %>
</p>

<p>
  <b>Project:</b>
  <%= @deliverable.project %>
</p>

<p>
  <b>Ticket:</b>
  <%= @deliverable.ticket %>
</p>

<p>
  <b>Description:</b>
  <%= @deliverable.description %>
</p>

<p>
  <b>Estimated task time:</b>
  <%= @deliverable.estimated_task_time %>
</p>

<p>
  <b>Estimated task resource time:</b>
  <%= @deliverable.estimated_task_resource_time %>
</p>

<p>
  <b>Cumulative time taskwise:</b>
  <%= @deliverable.cumulative_time_taskwise %>
</p>

<p>
  <b>Cumulative time resourcewise:</b>
  <%= @deliverable.cumulative_time_resourcewise %>
</p>

<p>
  <b>Week projected effort:</b>
  <%= @deliverable.week_projected_effort %>
</p>

<p>
  <b>Week actual effort:</b>
  <%= @deliverable.week_actual_effort %>
</p>

<p>
  <b>Qa release:</b>
  <%= @deliverable.qa_release %>
</p>

<p>
  <b>Production release:</b>
  <%= @deliverable.production_release %>
</p>

<p>
  <b>Release:</b>
  <%= @deliverable.release %>
</p>

<p>
  <b>Work list:</b>
  <%= @deliverable.work_list %>
</p>


<%= link_to 'Edit', edit_deliverable_path(@deliverable) %> |
<%= link_to 'Back', deliverables_path %>

app/views/home/index.html.erb
<h3>Home</h3>
<% @users.each do |user| %>
  <p>User: <%=link_to user.name, user %></p>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "P Status", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>        
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>  
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', users_path %>
      </li>
    <% end %>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "P Status" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/users/index.html.erb
<h3>Users</h3>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>